server:
  port: 8081

spring:
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: xiaoyuan
    password: root
  redis:
    port: 6379
    host: localhost
  # \u65F6\u95F4\u683C\u5F0F\u8F6C\u6362
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    # \u5F15\u5165application-email\u914D\u7F6E\u6587\u4EF6
    include: email

mybatis-plus:
  # mapper\u6587\u4EF6\u6620\u5C04\u8DEF\u5F84
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # \u6253\u5370SQL\u8BED\u53E5
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.shyroke.mapper: debug